server:
  port: 8761
eureka:
  instance:
    hostname: euraka-server
  client:
    register-with-eureka: false   #不把自己注册到euraka
    fetch-registry: false   #不从euraka拉取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/